import { Profile } from "@/profile";
import { Button, Heading, Image, VStack } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { ZKEdDSAEventTicketPCD } from "@pcd/zk-eddsa-event-ticket-pcd";
import useLocalStorage from "use-local-storage";
import { connect } from "@/connect";

export default function Connect() {
	const router = useRouter();
	const [authResult] = useLocalStorage<ZKEdDSAEventTicketPCD | null>('authResult', null);
	const [success, setSuccess] = useState(false);
	const [isClient, setIsClient] = useState(false);

	const [profile] = useLocalStorage<Profile | null>('profile', null);
	useEffect(() => {
		if (!profile) {
			router.push('/');
		}
		setIsClient(true);
		console.info(`Profile: ${JSON.stringify(profile)}`);
	}, [profile, router]);

	const { attendeeSemaphoreId, image, name } = router.query;

	const onClick = async () => {
		if (!profile) {
			throw new Error('Profile is missing');
		}

		if (!authResult?.claim.partialTicket.attendeeSemaphoreId) {
			throw new Error('attendeeSemaphoreId is missing');
		}

		if (typeof attendeeSemaphoreId !== 'string') {
			throw new Error('attendeeSemaphoreId is missing');
		}

		await connect(authResult?.claim.partialTicket.attendeeSemaphoreId, attendeeSemaphoreId);
		setSuccess(true);
	};

	return <>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<main>
			<VStack spacing={3}>
				<Heading>ZuMatch</Heading>
				{isClient ? (<>
					<Image src={image as string} alt={name as string} />
					<Heading>{name}</Heading>
					{success ? 'Success!' : (<><Button onClick={onClick}>Connect</Button> as {profile?.title}</>)};
				</>) : null}
			</VStack>
		</main>
	</>
}